### ISSUE TITLE
CallStaticMethod not found

### ISSUE THREAD

**Issue by schrepel** [Shazwazza/UmbracoIdentity#104]
Working with the UmbracoIdentity package in Umbraco 8.1.4, and lines 65 and 70 of the FrontEndCookieManager.cs that reference "CallStaticMethod" throw an error (type doesn't contain a definition for CallStaticMethod).

Also on those two lines, is it assumed that UriExtensions are basically Umbraco.Core.UriExtensions, or are those System.Net.Http.UriExtensions?

**Comment by Shazwazza** [comment]
`CallStaticMethod` is an ext method of this `https://github.com/Shazwazza/UmbracoIdentity/blob/master/src/UmbracoIdentity/ReflectionHelper.cs`

These calls are calling into Umbraco internal methods on Umbraco's `UriExtensions`, see https://github.com/umbraco/Umbraco-CMS/blob/v8/dev/src/Umbraco.Core/UriExtensions.cs#L42 and https://github.com/umbraco/Umbraco-CMS/blob/v8/dev/src/Umbraco.Core/UriExtensions.cs#L110
