### ISSUE TITLE
Needed to include "using UmbracoIdentity;" in UserPasswordModel.cs

### ISSUE THREAD

**Issue by DanielOor365** [Shazwazza/UmbracoIdentity#106]
I have set-up Umbraco 8.5.2, starting from the CodeShare Starter Kit.
( Set-up starter kit, upgrading to 8.5.2)

I then added the UmbracoIdentity nugget package.

When trying to compile, I got the following error in UserPasswordModel.cs :
... type or namespace name 'UmbracoMembersUserManager<>' could not be found ...

To resolve this, I added 
`using UmbracoIdentity;`
to the using directives in the UserPasswordModel.cs file.

The corrective solution would be to add  "using UmbracoIdentity;" to the UserPasswordModel.cs  file while installing the package.

**Comment by Shazwazza** [comment]
Thanks for the report, any chance you can submit a PR for this fix?

**Comment by DanielOor365** [comment]
Sure – Never done it before, but I will give it a go…

**Comment by Shazwazza** [comment]
Awesome thanks! 🎉
