### ISSUE TITLE
Log out issues with external providers

### ISSUE THREAD

**Issue by jpiombo** [Shazwazza/UmbracoIdentity#115]
Hi, 
I have been testing this implementation in Umbraco 8.6.1 and i have issues with external providers not logging out properly. IE) I logout from umbraco, but when i log in again, i am automatically logged in using external provider that i choose. Do you know what might be wrong or missing? 
This is happening for Auth0, Azure and facebook. 
Thanks!!

**Comment by Shazwazza** [comment]
what do you mean by 

> I logout from umbraco 

? This library is for front-end members, not back office users so do you mean log out from your front-end umbraco site or your back office?

**Comment by jpiombo** [comment]
Hi, not an issue anymore, it was some missconfiguration at my side.
