### ISSUE TITLE
UmbracoMembersUserManager<> not found after UmbracoIdentity NuGet installation

### ISSUE THREAD

**Issue by bogdan-khizhnyak** [Shazwazza/UmbracoIdentity#117]
**Steps to reproduce:**
- Install Umbraco following steps, described in the official [article](https://our.umbraco.com/documentation/getting-started/setup/install/install-umbraco-with-nuget).
- Include all Umbraco related folders into the project (required to make it compatible with MSBuild), 'App_Data' folder content is skipped, except 'packages' folder.
- Install UmbracoIdentity NuGet package and try to build solution.

**Actual result:**
Errors in file ../Models/UmbracoIdentity/UserPasswordModel - Error	CS0246	The type or namespace name 'UmbracoMembersUserManager<>' could not be found (are you missing a using directive or an assembly reference?)

_It could be fixed by adding following using construct to the above-mentioned file: using UmbracoIdentity;_

**Comment by Shazwazza** [comment]
Hi, i think this is the same as this error which was merged in already https://github.com/Shazwazza/UmbracoIdentity/pull/107 orig issue https://github.com/Shazwazza/UmbracoIdentity/issues/106

but oh my i haven't released that version yet! i will do this week sorry about that
