### ISSUE TITLE
How do I develop locally?

### ISSUE THREAD

**Issue by knnithyanand** [Shazwazza/UmbracoIdentity#119]
I want to extend the library to overcome certain limitations, such as adding Email / Phone Verification and 2FA support. I have a big challenge to develop and debug the code locally.

Objective:
Extend the UserManager & UserStore classes to add necessary features. Still, then I have to rewrite certain logic for mapping because some methods are private, and not all methods can be overridden. If I had to modify the source classes to include these features on my machine, I have to run build scripts and publish a NuGet package to a local folder and add them into my web project.

But this is not productive for a few reasons:
1. Have to publish package and update for every change
1. I cannot set breakpoints and debug the code

Here are some things I have tried:
- Run the reference web project in the repository
![image](https://user-images.githubusercontent.com/3396079/86534996-c0e6fe80-bf0f-11ea-9618-6108e5ac3a32.png)

- Create a new Umbraco project instead of installing NuGet package add project reference to the web project (also applied web.config transformations)
![image](https://user-images.githubusercontent.com/3396079/86534962-7f565380-bf0f-11ea-9eb3-d4610b08f420.png)

Both these attempts have failed, above are the errors for reference.

**Comment by jpiombo** [comment]
Where you able to extend the user manager without modifying the source code? 

Eg; using this? https://github.com/Shazwazza/UmbracoIdentity/wiki/Startup-Configuration

I just want to extend the lockout functionality and was not able to do so.

**Comment by Shazwazza** [comment]
The web project included in this solution is there for developing locally. 

* Open the solution in VS
* In the nuget package manager console re-install the UmbracoCms package: `Update-Package UmbracoCms -Project UmbracoIdentity.Web -Reinstall`
* Start the website and run the install, etc... like normal
* You'll need to create the Account document type and template but be sure to not overwrite the Account.cshtml template file in the source, or let it overwrite it and then revert it back to normal

**Comment by knnithyanand** [comment]
> Where you able to extend the user manager without modifying the source code? 
> 
> 
> 
> Eg; using this? https://github.com/Shazwazza/UmbracoIdentity/wiki/Startup-Configuration
> 
> 
> 
> I just want to extend the lockout functionality and was not able to do so. 

Yes, I was able to. I'm adding email verification function this way.

**Comment by knnithyanand** [comment]
`Update-Package UmbracoCms -Project UmbracoIdentity.Web -Reinstall` works for me. Thanks a lot.
