### ISSUE TITLE
Exception after deployment to Azure 2012 R2 web role

### ISSUE THREAD

**Issue by bdongus** [Shazwazza/UmbracoIdentity#12]
Dear Shazwazza.

After deploying to an Azure web role I ended up with the following exception:
Exception message: Unable to load the native components of SQL Server Compact corresponding to the ADO.NET provider of version 8876. Install the correct version of SQL Server Compact. Refer to KB article 974247 for more details.

It seems only the x86 version is included in the nuget package.

Kind regards
Bernd

**Comment by Shazwazza** [comment]
That seems odd as it's just using the assemblies for SQLCE that are shipped with Umbraco which include all of the required assemblies for SQLCE to work in any environment. Are you sure you published all umbraco assemblies that we normally ship with to this environment?

In newer versions I'll be storing the external login information in the standard DB that you install Umbraco to. You can do this now with UmbracoIdentity but you need to configure the db tables yourself and update the user store connection string properly.

**Comment by bdongus** [comment]
I had all assemblies in the bin folder published. After installing SQLCE on the web role it worked.
Having the data in the standard DB is most probably the best approach. That as a new feature, would be nice.
