### ISSUE TITLE
Limit Google log-ins to one GSuite domain

### ISSUE THREAD

**Issue by setsqr** [Shazwazza/UmbracoIdentity#123]
Hi,

I'm looking into limiting Google log-ins to only those which belong to a particular GSuite domain.  For example, a university would like anybody with a university-provided email address (as set up and managed in that organisation's GSuite account) to be able to authenticate, but nobody else.

There is a parameter `hd` in the Google documentation (https://developers.google.com/identity/protocols/oauth2/openid-connect#hd-param) which looks like it does this.  My question is, is this something that is implemented in UmbracoIdentity?  If not, would it be feasible to extend it to do so.  I'm not particularly familiar with how all of this is set up at the moment so it's a learning curve and I'm just trying to gauge feasibility, presently.

Many thanks.

**Comment by Shazwazza** [comment]
Hi, yes that should be possible using one of the callbacks provided with the google OAuth client code. Something like:

```cs
var googleOptions = new GoogleOAuth2AuthenticationOptions
{
        // ... other settings are here
	
	Provider = new GoogleOAuth2AuthenticationProvider
	{
		OnAuthenticated = context =>
		{
			// You could run code here to validate the context
		}
	}
```

Or you could override the default google auth handler. UmbracoIdentity doesn't do anything with external log providers, it just facilitates the linking of them to Members, it's entirely up to you to define how your external login providers work. I found a pretty detailed thread on SO about this question which might help too https://stackoverflow.com/questions/29150989/limit-user-authorization-to-my-google-domain

**Comment by setsqr** [comment]
That's super helpful, thank you Shannon :)
