### ISSUE TITLE
wiki needs updating the integration guides no longer exist.

### ISSUE THREAD

**Issue by John-Blair** [Shazwazza/UmbracoIdentity#125]
Following links no longer exist in the wiki

 https://github.com/Shazwazza/UmbracoIdentity/wiki/External-Authentication-(OAuth)

https://pstokes.co.uk/posts/umbraco-members-and-identity-server-part-1/
https://pstokes.co.uk/posts/umbraco-members-and-identity-server-part-2/
https://pstokes.co.uk/posts/umbraco-members-and-identity-server-part-3/

Label: Observation

**Comment by Shazwazza** [comment]
that's a shame I guess whoever wrote those has abandoned their blog and project. thanks for the report
