### ISSUE TITLE
Error on installing: "A drive with the name 'http' does not exist"

### ISSUE THREAD

**Issue by sri7vasu** [Shazwazza/UmbracoIdentity#13]
Hi 

I am getting the following error when installing the nuget package using the command : Install-Package UmbracoIdentity

Split-Path : Cannot find drive. A drive with the name 'http' does not exist.
At C:\Users\SAtta\Documents\WebMatrix Solutions\Projects\packages\UmbracoCms.Core.7.2.4\tools\install.ps1:5 char:37
+     $backupPath = Join-Path (Split-Path <<<<  $project.FullName -Parent) "\App_Data\NuGetBackup\$dateTime"
    + CategoryInfo          : ObjectNotFound: (http:String) [Split-Path], DriveNotFoundException
    + FullyQualifiedErrorId : DriveNotFound,Microsoft.PowerShell.Commands.SplitPathCommand

Please help !

Thanks,
Srini

**Comment by Shazwazza** [comment]
That is an issue with the Umbraco nuget installer. I'm assuming you are using a website project (as opposed to a web application project). 

I've logged an issue on the umb core: http://issues.umbraco.org/issue/U4-6560

In the meantime if you create a web application project in VS and install Umbraco you shouldn't (in theory) get that error). I'm also not sure if that error has any real affect on Umbraco installation, does it still work?

**Comment by sri7vasu** [comment]
yes i am using a website project. Will create a Web appplication , add my Umbraco files and try. 
Actually that error do not have any affect on Umbraco installation. Thank you very much for the prompt response. I am kind of pulling my hair since past few hours.

**Comment by Shazwazza** [comment]
You can probably just continue without a webapp since it probably installed just fine anyways.

**Comment by sri7vasu** [comment]
Actually once i am stuck with the error during the nuget installation, its inducing a build error too. So My web page isnt loading successfully too. I have to reload the default Umbraco files from the download and do the initial configuration stuff to run.

**Comment by Shazwazza** [comment]
ok, well maybe start with a web app and go from there. I'll close this for now since it's an Umbraco core issue.

**Comment by sri7vasu** [comment]
Ok, will try the web app for now. Is there any way its possible to correct the issue and re push the package to nuget ?

**Comment by Shazwazza** [comment]
no that is not possible unfortunately without publishing a new version.

**Comment by sri7vasu** [comment]
Nuget installation Worked like a charm when converted to a web application

**Comment by sri7vasu** [comment]
I am able to install the nuget package successfully after cinvertibg to web application, but it really didnt do any changes to my project habce couldn't see the identity related code files. Can you provide some steps to integrate the source code manually ?
