### ISSUE TITLE
Using with Umbraco v7.3.0 RC

### ISSUE THREAD

**Issue by BenFidge** [Shazwazza/UmbracoIdentity#14]
Hi Shannon

I've just fired 7.3.0 RC into a blank MVC 5 application and installed UmbracoIdentity nuget package. Then configured it as per the instructions at

https://github.com/Shazwazza/U...

I set <add key="owin:AutomaticAppStartup" value="true"/> in web.config so OWIN finds the auto-generated UmbracoIdentityStartup class UmbracoIndentity nuget package creates.

For back-office authentication to work i call AppBuilderExtensions.ConfigureUserManageForUmbracoBackOffice and AppBuilderExtensions.UseUmbracoBackOfficeExternalCookieAuthentication at the start of UmbracoIdentityStartup.Configuration

I can log into back-office fine, and having configured my facebook app, theres a button for it displayed in ExternalLoginsList.cshtml.

HOWEVER, when i try to register a front-end member either using facebook or manual registration, I get the following error:

Cannot execute without a valid/current UmbracoContext with an HttpContext assigned.

Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code.

Exception Details: System.NotSupportedException: Cannot execute without a valid/current UmbracoContext with an HttpContext assigned.

Source Error:

Line 332: };
Line 333:
Line 334: var result = await UserManager.CreateAsync(user, model.Password);
Line 335: if (result.Succeeded)
Line 336: {

Source File: d:\Projects\Test Projects\Umbraco OAuth\Umbraco OAuth\Controllers\UmbracoIdentityAccountController.cs Line: 334

The member is actually created however and shows under back-offce member. I can also login to the front-end using its credentials

**Comment by alecrt** [comment]
I think this is related to [U4-6495](http://issues.umbraco.org/issue/U4-6495)

**Comment by Shazwazza** [comment]
This issue was due to the incorrect way I was using the async methods. this has all be fixed up.
