### ISSUE TITLE
Umbraco Identity for Umbraco 9

### ISSUE THREAD

**Issue by daljitkaur9** [Shazwazza/UmbracoIdentity#145]
Hi Shannon,

UmbracoIdentity is a really nice package that we have already used in one of our Umbraco 8 projects, in which we needed to have Azure Ad B2C authentication for the umbraco members.

Now We have the same requirement but the project this time is using Umbraco 9.
I have tried to follow all the .net 5 with Azure B2C tutorials & articles but i am not getting the right solution.
 
I know this not exactly an issue :) but just wondering if there is anything out there that will  make the process easier in Umbraco 9 ?

**Comment by Shazwazza** [comment]
This library will only support Umbraco 8. All ASP.NET Identity services for umbraco members are included in v9 directly. The process will be made easier in the future within v9. I posted some information here https://github.com/umbraco/Umbraco-CMS/issues/10656#issuecomment-896245280

**Comment by wvankesteren-ax** [comment]
Thanx for pointing to your comment in https://github.com/umbraco/Umbraco-CMS/issues/10656#issuecomment-896245280.
We hope it will be very soon it will be implemented!
