### ISSUE TITLE
UmbracoIdentity For Umbraco 9 (ASP.NET Core)

### ISSUE THREAD

**Issue by Ibrahimogod** [Shazwazza/UmbracoIdentity#148]
Hey Shazwazza,

Wish you're doing well, hope you have time to replay for this, are you gonna provide a new NuGet package for Umbraco 9 If yes can you let us know when Exactly its gonna be published 

thanks & Regards,
 Ibrahim Ahmed Badr

**Comment by Shazwazza** [comment]
Hi, please see this ticket https://github.com/Shazwazza/UmbracoIdentity/issues/145
