### ISSUE TITLE
Umbraco logs flooded with access_denied

### ISSUE THREAD

**Issue by Sven883** [Shazwazza/UmbracoIdentity#151]
Hello! 

We've integrated Azure Active Directory B2C (using this [guide](https://24days.in/umbraco-cms/2019/aad-and-headless/umbraco8-aadb2c/)) into our project, but we're having a 'problem', our logs are getting flooded with the following logs: 

```
[Error] Event Id: 0, State: "\"OpenIdConnectMessage.Error was not null, indicating an error. Error: 'access_denied'. Error_Description (may be empty): 'AADB2C90118: The user has forgotten their password.
Correlation ID: XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX
Timestamp: 2021-11-30 09:19:02Z
login_hint: user@user.be
'. Error_Uri (may be empty): 'error_uri is null'.\""
```

```
Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectProtocolInvalidNonceException: IDX21323: RequireNonce is '[PII is hidden]'. OpenIdConnectProtocolValidationContext.Nonce was null, OpenIdConnectProtocol.ValidatedIdToken.Payload.Nonce was not null. The nonce cannot be validated. If you don't need to check the nonce, set OpenIdConnectProtocolValidator.RequireNonce to 'false'. Note if a 'nonce' is found it will be evaluated.
   at Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectProtocolValidator.ValidateNonce(OpenIdConnectProtocolValidationContext validationContext)
   at Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectProtocolValidator.ValidateAuthenticationResponse(OpenIdConnectProtocolValidationContext validationContext)
   at Microsoft.Owin.Security.OpenIdConnect.OpenIdConnectAuthenticationHandler.<AuthenticateCoreAsync>d__11.MoveNext()
```

Any idea how to solve this?

**Comment by Shazwazza** [comment]
I'm not sure, there's many many options for each OAuth provider and this error seems to indicate it's the OAuth integration and not UmbracoIdentity. This library only links the external identities to Umbraco via ASP.NET Identity, it's not responsible for the actual OAuth integration. 

You will need to investigate this issue with regards to Active Directory B2C and adjust your OAuth integration settings accordingly. For debugging, you should enable "PII" to be shown in your OAuth settings. Based on your error, the Nonce is not being validated, this is part of your OAuth integration/configuration. However, the Nonce may not be validated based on your initial error `AADB2C90118: The user has forgotten their password` which you will need to investigate. 

Unfortunately that is all the help I can provide. The issues are directly related to the OAuth integration, not this library.
