### ISSUE TITLE
Where Does Phone Number's been stored

### ISSUE THREAD

**Issue by Ibrahimogod** [Shazwazza/UmbracoIdentity#152]
I'm Trying To retrieve Phone Number after user Register but it returns Null I tried to check database to see its field but I found no column refers to Phone Number and there's no property for phone number in umbracoMember Document Type
```
        public async Task<UserInfoViewModel> GetUserInfoAsync(IPrincipal user)
        {
            var member = await UserManager.FindByIdAsync(user.Identity.GetUserId<int>());
            var userData = ContentQuery.Content(int.Parse(GetUserDataId(user.Identity.GetUserId<int>())))?.ToObject<UserData>();
            return new UserInfoViewModel()
            {
                Name = member.Name,
                Email = member.Email,
                PhoneNumber = member.PhoneNumber,
                Address = userData.Address,
                City = userData.City,
                ResidenceNumber = userData.ResidenceNumber,
                ProfilePicture = userData.ProfilePicture
            };
        }
```
This Method returns
```
 {
   
      "Name": "Ibrahim Ahmed Badr",

       "Email": "ibadr2122000@gmail.com",

       "ResidenceNumber": 12100479,
```

       **"PhoneNumber": null,**

```
       "City": "Cairo",

       "Address": "Al-Seha street Ain Shams",

       "ProfilePicture": null
}
```
hope someone can Help

**Comment by Shazwazza** [comment]
UmbracoIdentity doesn't implement any additional features and storage to what Umbraco provides. This is an ASP.NET Identity wrapper around the services that Umbraco provides. If you wish to expand the feature set of UmbracoIdentity, you will need to implement the remaining Identity services and interfaces yourself. This is noted in the [docs](https://github.com/Shazwazza/UmbracoIdentity) under ["known issues and limitations"](https://github.com/Shazwazza/UmbracoIdentity/wiki/Known-Issues)
