### ISSUE TITLE
Is there a AzureAD extension available??

### ISSUE THREAD

**Issue by vnetonline** [Shazwazza/UmbracoIdentity#19]

**Comment by Shazwazza** [comment]
Yes, the OAuth Identity provider for AzureAD is `Microsoft.Owin.Security.OpenIdConnect`

Here's some notes on it's implementation. Most details here: https://github.com/Azure-Samples/active-directory-dotnet-webapp-webapi-openidconnect and there's code here for the back office implementation in 7.3 here which you can probably borrow some inspiration from for the front-end: https://github.com/umbraco/UmbracoIdentityExtensions/blob/master/src/App_Start/UmbracoADAuthExtensions.cs
