### ISSUE TITLE
Suggestion: Move .cshtml files to a seperate nuget project

### ISSUE THREAD

**Issue by rasmuseeg** [Shazwazza/UmbracoIdentity#22]
This will allow developers to install the package based on either foundation, bootstrap etc.

**Comment by Shazwazza** [comment]
Though this would also require making all of the cshtml files for another framework. I think the point of shipping with foundation is simply to provide examples, but if you think it's important to ship with examples based on other styles then those would have to be created.

**Comment by rasmuseeg** [comment]
Yes, but my company requires that i use bootstrap. So I've created most of it anyways

**Comment by Shazwazza** [comment]
I'm closing this issue since in 4.0.0 we do ship two separate packages: one for the core dlls and one for the code snippets. 

There's not much i can do about the foundation vs bootstrap thing, I'm shipping these views as a reference for how to make things, not particularly that you must use them.
