### ISSUE TITLE
SecurityStampValidator Cause logout

### ISSUE THREAD

**Issue by OlivierAlbertini** [Shazwazza/UmbracoIdentity#25]
Hi,

```
            app.UseCookieAuthentication(new CookieAuthenticationOptions
            {
                AuthenticationType = DefaultAuthenticationTypes.ApplicationCookie,
                Provider = new CookieAuthenticationProvider
                {
                    // Enables the application to validate the security stamp when the user 
                    // logs in. This is a security feature which is used when you 
                    // change a password or add an external login to your account.  
                    OnValidateIdentity = SecurityStampValidator
                        .OnValidateIdentity<UmbracoMembersUserManager<UmbracoApplicationMember>, UmbracoApplicationMember, int>(
                            TimeSpan.FromMinutes(30),
                            (manager, user) => user.GenerateUserIdentityAsync(manager),
                            UmbracoIdentity.IdentityExtensions.GetUserId<int>)
                }
            });
```

After some investigation, I found that SecurityStampValidator cause user to logout depending `TimeSpan.FromMinutes(30)`

If I comment these lines :

```
 Provider = new CookieAuthenticationProvider
                {
                    // Enables the application to validate the security stamp when the user 
                    // logs in. This is a security feature which is used when you 
                    // change a password or add an external login to your account.  
                    OnValidateIdentity = SecurityStampValidator
                        .OnValidateIdentity<UmbracoMembersUserManager<UmbracoApplicationMember>, UmbracoApplicationMember, int>(
                            TimeSpan.FromMinutes(30),
                            (manager, user) => user.GenerateUserIdentityAsync(manager),
                            UmbracoIdentity.IdentityExtensions.GetUserId<int>)
                }
```
Everything works fine, but It should be great to have this feature ...

During the investigation, I noticed that : 
(I don't know if it's for that ..)

![identity](https://cloud.githubusercontent.com/assets/3801683/11166135/a1af63d4-8af5-11e5-9330-b3a022a77864.png)

It's my first project with identity so if you have suggestion, I will be happy to hear it !

**Comment by Shazwazza** [comment]
What version of Umbraco are you using ?

**Comment by OlivierAlbertini** [comment]
I sorry for the delay. I was using 7.3.1

Now, I'm using 7.3.3 and I followed your documentation. I use owin standard startup file but now, "security stamp" doesn't and I can't be logged front-end and back-end at the same time... I need to logout in front-end in order to be logged in backend... Of course, if I use 2 different browsers, this workaround works (or private navigation too) but still complex to explain that for content-editor (this is not an habit)... moreover, I can't find a workaround for having a " preview" feature in umbraco back-end when the page has a restricted access.

```csharp
using Microsoft.AspNet.Identity.Owin;
using Microsoft.Owin;
using Microsoft.Owin.Security.Cookies;
using Microsoft.Owin.Security.Google;
using UmbracoIdentity;
using DicomIntranet.Models.UmbracoIdentity;
using DicomIntranet;
using Owin;

using Umbraco.Web;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNet.Identity;
using System;
using System.Configuration;
using Microsoft.AspNet.SignalR;


//To use this startup class, change the appSetting value in the web.config called 
// "owin:appStartup" to be "UmbracoStandardOwinStartup"

[assembly: OwinStartup("UmbracoStandardOwinStartup", typeof(UmbracoStandardOwinStartup))]

namespace DicomIntranet
{
    /// <summary>
    /// The standard way to configure OWIN for Umbraco
    /// </summary>
    /// <remarks>
    /// The startup type is specified in appSettings under owin:appStartup - change it to "StandardUmbracoStartup" to use this class
    /// </remarks>
    public class UmbracoStandardOwinStartup : UmbracoDefaultOwinStartup
    {
        public override void Configuration(IAppBuilder app)
        {
            //ensure the default options are configured
            base.Configuration(app);

            

            //Single method to configure the Identity user manager for use with Umbraco
            app.ConfigureUserManagerForUmbracoMembers<UmbracoApplicationMember>();



            // Enable the application to use a cookie to store information for the 
            // signed in user and to use a cookie to temporarily store information 
            // about a user logging in with a third party login provider 
            // Configure the sign in cookie
            app.UseCookieAuthentication(new CookieAuthenticationOptions
            {
                AuthenticationType = DefaultAuthenticationTypes.ApplicationCookie,
                //CookieDomain = ConfigurationManager.AppSettings["CookieDomain"].ToString(),
                CookieName = ConfigurationManager.AppSettings["CookieName"].ToString(),
                SlidingExpiration = true
            });

            app.UseExternalSignInCookie(DefaultAuthenticationTypes.ExternalCookie);


            GoogleOAuth2AuthenticationOptions options = new GoogleOAuth2AuthenticationOptions()
            {
                ClientId = ConfigurationManager.AppSettings["GoogleAppId"].ToString(),
                ClientSecret = ConfigurationManager.AppSettings["GooglekAppSecret"].ToString(),
                Provider = new GoogleOAuth2AuthenticationProvider()
                {

                    OnAuthenticated = (context) =>
                    {
                        context.Identity.AddClaim(new Claim("image", context.User.GetValue("image").ToString()));
                        return Task.FromResult(0);
                    }
                }
            };
            //options.Scope.Add("https://www.googleapis.com/auth/userinfo.email");
            app.UseGoogleAuthentication(options);

            string connectionString =ConfigurationManager.AppSettings["SignalrAppSecret"].ToString();
            GlobalHost.DependencyResolver.UseServiceBus(connectionString, "signalr");

            app.MapSignalR();

        }
    }
}
```
If you have any idea that can help me, it will be appreciated !

**Comment by Shazwazza** [comment]
Hi, it is a known issue with Umbraco that you cannot preview protected pages: http://issues.umbraco.org/issue/U4-4219

Please review the upcoming fixes for 7.3.5: 

* http://issues.umbraco.org/issues/U4?q=Due+in+version%3A+7.3.5+

And you can also review the updates for versions between 7.3.1 -> 7.3.4 since they also probably contain some fixes for the Identity implementation for the back office in Umbraco.

Please test against the latest version of Umbraco and let me know of any differences that makes with regards to being logged in to the front-end + the back office at the same time - this should work - but previewing protected pages will not due to the known Umbraco issue (that is tricky to fix because of the nature of ASP.Net = there is only one User object on the request)

**Comment by Shazwazza** [comment]
I'm not sure if this is part of the issue you are seeing but in Umbraco 7.3.4 + UmbracoIdentity, I can successfully log in to the front-end + the back office at the same time. However, if I log out of the back office, this will also log me out of the front-end. If this is one of the issues you are referring to, this is fixed in the next umbraco release: http://issues.umbraco.org/issue/U4-7536

**Comment by Shazwazza** [comment]
I have also just confirmed that when setting the SecurityStampValidator, that the front-end member does get logged out after the timespan set there. I'm investigating why this is happening.

**Comment by Shazwazza** [comment]
I have verified why this is the case:

* We are using a custom UserManager which currently does not support a Security Stamp: https://github.com/Shazwazza/UmbracoIdentity/blob/master/src/UmbracoIdentity/UmbracoMembersUserManager.cs#L42
* I was naive and unaware that this was a requirement to use the `OnValidateIdentity = SecurityStampValidator` syntax, I was also unaware that in the ASP.Net identity code that it will force log out the user if this syntax is specified but the UserManager does not support this option

So to fix this issue, we need to update this project to support the `SupportsUserSecurityStamp` flag. In the meantime, you cannot use the SecurityStampValidator. I will update the docs and the classes shipped with this project to remove this syntax to not cause any confusion.

I will close this issue with a work-around posted and create another task/issue to support `SupportsUserSecurityStamp`

**Comment by Shazwazza** [comment]
Linking to this issue: https://github.com/Shazwazza/UmbracoIdentity/issues/30
