### ISSUE TITLE
Extending UmbracoMembersUserManager

### ISSUE THREAD

**Issue by alecrt** [Shazwazza/UmbracoIdentity#26]
Dear Shazwazza,

we would like to extend your UmbracoMembersUserManager<T> class in order to include support for additional features (Ex. custom EmailService, UserLockout etc..).

We found a problem trying overriding some functions: both MembershipPasswordHasher and ExternalLoginStore for example are internal classes.

Any suggestion on how achieving this?

Thank you,
Alessandro

**Comment by Shazwazza** [comment]
You can

**Comment by Shazwazza** [comment]
I've made those classes public

**Comment by alecrt** [comment]
Hi Shannon,

just a side note: there's something weird in the latest nuget package (v 3.01).
MembershipPasswordHasher class is still internal.

The source code released as version 3.0 on Github, instead, is fine.

Thank you, A.

**Comment by Shazwazza** [comment]
oh that's odd! I'll push another version up there today.

**Comment by Shazwazza** [comment]
I have pushed a new 3.0.2 version to Nuget.

**Comment by alecrt** [comment]
Thank you very much!
