### ISSUE TITLE
Missing files

### ISSUE THREAD

**Issue by JayCoady34** [Shazwazza/UmbracoIdentity#27]
After I have installed the Nuget package I do not see the  classes you mention should be added to the App_Start folder: UmbracoApplicationUser and UmbracoStartup.

I am running the latest version Umbraco Cms 7.3.1

**Comment by Shazwazza** [comment]
Are you using a Website or Web app ? If you are using a website, the files are installed into App_Code

**Comment by JayCoady34** [comment]
ASP.net MVC 4 Web App

**Comment by Shazwazza** [comment]
It was an issue with the documentation which has now been updated: https://github.com/Shazwazza/UmbracoIdentity
