### ISSUE TITLE
UmbracoIdentity on version 7.3

### ISSUE THREAD

**Issue by alinadonisa** [Shazwazza/UmbracoIdentity#29]
Hi Shannon,

I have used  UmbracoIdentity with  version 7.2.6 of Umbraco and it worked the way I was expecting. After I have upgraded Umbraco  to version 7.3.4 (I need this version for the translations fix). it seems there are some breaking changes in the code. Please check my photos.

I also have a custom membership provider that I need to use. I added a print screen of the UmbracoIdentityStartup class, to see how I am using it.

When I comment the lines that check for auth (check print screens), deploy the modifications, and try to access the user site I get 401 error, the back office instead it works fine. When I use the application from local server it works fine.(no 401 error).

Please advise!
Thanks!

![umbracoshouldauthcommented](https://cloud.githubusercontent.com/assets/11087269/11687194/d5ac745a-9e8d-11e5-8dfa-3d1b9479310f.png)

![umbracoidentityerror](https://cloud.githubusercontent.com/assets/11087269/11686773/87c65794-9e8b-11e5-99b0-6b8bd21fd681.png)

![umbracoidentitystartup](https://cloud.githubusercontent.com/assets/11087269/11687009/06797750-9e8d-11e5-8f50-9d2615975294.png)

**Comment by rasmuseeg** [comment]
Hi @alinadonisa 

Try outcommenting, like so:
//base.Configuration(app);

and add this below:
app.SetDefaultSignInAsAuthenticationType(CookieAuthenticationDefaults.AuthenticationType);

**Comment by alinadonisa** [comment]
Hi,
Thanks for your quick answer. Unfortunately it gives me 401 when I deploy it... I have changed to use the UmbracoStandardOwinStartup, and I added the code below, but the same: I get 401 on deploy.  

  public override void Configuration(IAppBuilder app)
        {
            //ensure the default options are configured
            base.Configuration(app);
            app.SetDefaultSignInAsAuthenticationType(CookieAuthenticationDefaults.AuthenticationType);
            //Single method to configure the Identity user manager for use with Umbraco
            app.ConfigureUserManagerForUmbracoMembers<UmbracoApplicationMember>(ApplicationContext.Current,
                membershipProvider: System.Web.Security.Membership.Providers["UmbracoMembershipProvider"] as SmurfsMembershipProvider);
             app.UseCookieAuthentication(new CookieAuthenticationOptions
             {
                 AuthenticationType = DefaultAuthenticationTypes.ApplicationCookie,

                 Provider = new CookieAuthenticationProvider
                 {
                     // Enables the application to validate the security stamp when the user 
                     // logs in. This is a security feature which is used when you 
                     // change a password or add an external login to your account.  
                     OnValidateIdentity = SecurityStampValidator
                         .OnValidateIdentity<UmbracoMembersUserManager<UmbracoApplicationMember>, UmbracoApplicationMember, int>(
                             TimeSpan.FromMinutes(30),
                             (manager, user) => user.GenerateUserIdentityAsync(manager),
                             UmbracoIdentity.IdentityExtensions.GetUserId<int>)
                 }
             });
             app.ConfigureBackOfficeGoogleAuth(ConfigurationHelper.GetSettingAsString("GoogleClientId"), ConfigurationHelper.GetSettingAsString("GoogleClientSecret"));
             app.ConfigureBackOfficeFacebookAuth(ConfigurationHelper.GetSettingAsString("FacebookAppId"), ConfigurationHelper.GetSettingAsString("FacebookAppSecret"));

**Comment by rasmuseeg** [comment]
Hi @alinadonisa you forgot to outcomment
`//base.Configuration(app);`

**Comment by alinadonisa** [comment]
Hi, 
 I get the same...:( 401
![image](https://cloud.githubusercontent.com/assets/11087269/11710867/189fa08c-9f2b-11e5-8ccc-f061d538763d.png)

**Comment by rasmuseeg** [comment]
Not sure i can help you then.

**Comment by alinadonisa** [comment]
Ok.. Thanks I will rewrite using the new implementation from umbraco 7.3.

**Comment by Shazwazza** [comment]
Hi all, sorry have been on holidays. I think the main issue is that this package was using Internals/reflection and the APIs have changed in the core so will need to fix up.

Hopefully I'll get some time this week.

**Comment by Shazwazza** [comment]
closing this issue as it should be fixed with the 3.x versions
