### ISSUE TITLE
Custom SetEmailConfirmedAsync in UmbracoMembersUserStore

### ISSUE THREAD

**Issue by tonag** [Shazwazza/UmbracoIdentity#31]
Hi, I'am trying to implement   SetEmailConfirmedAsync that is still not implemented.
Is it possible to set it as virtual so it is easy to override it  while it is not implemented?
Is it possible to do the same for all the other not implemented functions?
Thanks for your job.
G.

**Comment by tonag** [comment]
Hi again, another problem I met is tat if I create a custom store copying your UmbracoMembersUserStore I can't use reflectionHelper for user properties because it is internal.
Thanks again.
G.

**Comment by Shazwazza** [comment]
Hi, these methods don't need to be virtual, they are part of the `IUserEmailStore` interface so you just need to implement that interface and for any method you want to 'override' you implement that method explicitly - this is the same as overriding.

**Comment by tonag** [comment]
Thank you very much, you solved my problem.
G.
