### ISSUE TITLE
Store does not implement IUserRoleStore<TUser>

### ISSUE THREAD

**Issue by rasmuseeg** [Shazwazza/UmbracoIdentity#33]
UserManager.AddToRole throws exception

**Comment by Shazwazza** [comment]
it is a known issue, see docs: https://github.com/Shazwazza/UmbracoIdentity/wiki/Known-Issues

**Comment by rasmuseeg** [comment]
Sorry about. Forgot to take a look.

**Comment by Shazwazza** [comment]
we can leave this open as a future task.

**Comment by Shazwazza** [comment]
You can implement this yourself though if you require role support in the meantime.

**Comment by rasmuseeg** [comment]
Btw the link on the page referenced "See '[Custom Startup/Configuration](https://github.com/Shazwazza/UmbracoIdentity/Startup-Configuration)' for further details on this." doesn't work.

For now, i just use the Services.MemberService.AssignRole(string username, string role);

**Comment by Shazwazza** [comment]
thanks, link is fixed

**Comment by Shazwazza** [comment]
This is implemented now
