### ISSUE TITLE
Exception establishing a connection to SQL Server for for UmbracoIdentity DB

### ISSUE THREAD

**Issue by terryclancy** [Shazwazza/UmbracoIdentity#35]
Shazwazza thanks for your assistance in solving Issue #32 ( https://github.com/Shazwazza/UmbracoIdentity/issues/32 ).

I am now beyond that but now having a weird error I am finding it hard to debug:

I am now on Umbraco 7.3.5 and after I Nuget Install-Package UmbracoIdentity  I  commented out the following line in web.config to cause the "Configuration" method of the Startup class to run:

    

The Configuration method of the Startup Class calls:

    ConfigureAuth(app);

When ever that method runs, sometime later during startup I get the following exception:

System.Data.SqlClient.SqlException occurred
  HResult=-2146232060
  Message=A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: SQL Network Interfaces, error: 26 - Error Locating Server/Instance Specified)
  Source=.Net SqlClient Data Provider
  ErrorCode=-2146232060
  Class=20
  LineNumber=0
  Number=-1
  Server=""
  State=0
  StackTrace:
       at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
  InnerException: 

I think (but not sure) that this Exception happens when trying to access the  Local SQL CE database used by the Identity and Authentication code (in my case "aspnet-TeraTastic-20160115064531.mdf"). 

I have spent a lot of time trying to get a handle on this but because the exception does not happen in my code it is difficult to debug. Any guidance would be appreciated.

ALSO  I note at https://our.umbraco.org/forum/umbraco-7/using-umbraco-7/73192-73-identity-issues#comment-234717 that you (Shannon Deminick) suggest installation of UmbracoCms.IdentityExtensions along with UmbracoIdentity,  but your docs for UmbracoIdentity say nothing about that.  Is it required ? Does it help ?

Thanks again

Terry Clancy (Australian in Bellevue WA USA)

ClanceZ

**Comment by terryclancy** [comment]
OK so this problem has gone away and I can not long reproduce it  So I would close this issue (at least for now or until I can reproduce it)

Something I did caused the creation of a local Database called aspnet-TeraTastic-20160117124334.mdf and then the installation seemed to have a problem accessing it.  But after a clean installation using

     Install-Package UmbracoCms 
     Run Umbraco (and related Installation wizard) and Log into back office
     Install-Package UmbracoIdentity
     Run Umbraco and Log into back office

The  local database was then absent.  Not sure why it was there in the first place, but I think this issue should be closed until I determine that this is a real issue and  can get a clearer definition of it.

I would still like to know if UmbracoCms.IdentityExtensions is recommended or required with UmbracoIdentity.

Also I now have another problem but will raise that as a separate issue to avoid confusion.

Thanks again

Terry Clancy

ClanceZ

**Comment by Shazwazza** [comment]
Hi,

* UmbracoIdentity = ASP.Net Identity implementation for **front-end members**, this has nothing to do with Identity Extensions
* Identity Extensions = ASP.Net Identity code snippets and token server for **back office users** which has nothing to do with UmbracoIdentity

Your problem is because you've removed:

```
<add key="owin:appStartup" value="UmbracoDefaultOwinStartup" />
```

I'm not sure why you've done this, this has completely disabled the Umbraco OWIN startup code. I will reply to your other issue about this.
