### ISSUE TITLE
Could not resolve an instance of Umbraco.Core.Security.BackOfficeSignInManager from the Microsoft.Owin.IOwinContext

### ISSUE THREAD

**Issue by terryclancy** [Shazwazza/UmbracoIdentity#36]
Hi again :-)

After a new clean installation of Umbraco Identity on Umbraco 7.3.5 using the following procedure

     Install-Package UmbracoCms 
     Run Umbraco (and related Installation wizard) and Log into back office (All OK)
     Install-Package UmbracoIdentity
     Run Umbraco and Log into back office (All OK)

I then commented out the following line in web.config to cause the "Configuration" method (and related call to ConfigureAuth(app) ) of the Startup class to run:

    

This caused the Error/Exception below to occur.

Note that this same Error/Exception occurs even after adding the following to the Configuration method of the Startup Class after ConfigureAuth(app):

Using the following includes

    using TeraTastic.Models.UmbracoIdentity;
    using Umbraco.Core;
    using Umbraco.Web.Security.Identity;
    using UmbracoIdentity;

I added the following code:

            //Single method to configure the Identity user manager for use with Umbraco
            app.ConfigureUserManagerForUmbracoMembers<UmbracoApplicationMember>();
            //Ensure owin is configured for Umbraco back office authentication
            app.UseUmbracoBackOfficeCookieAuthentication(ApplicationContext.Current);

Here is the Error/Exception:

Received an error from the server

```
Login failed for user terryclancy@live.com

Could not resolve an instance of Umbraco.Core.Security.BackOfficeSignInManager from the Microsoft.Owin.IOwinContext

Exception Details: 
 System.NullReferenceException: Could not resolve an instance of Umbraco.Core.Security.BackOfficeSignInManager from the Microsoft.Owin.IOwinContext 

Stacktrace: 
at Umbraco.Web.Editors.AuthenticationController.get_SignInManager()
   at Umbraco.Web.Editors.AuthenticationController.<PostLogin>d__f.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Threading.Tasks.TaskHelpersExtensions.<CastToObject>d__3`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.ActionFilterAttribute.<ExecuteActionFilterAsyncCore>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.ActionFilterAttribute.<ExecuteActionFilterAsyncCore>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Dispatcher.HttpControllerDispatcher.<SendAsync>d__1.MoveNext()
```

Thanks for everything

Terry Clancy

ClanceZ

**Comment by Shazwazza** [comment]
Your problem is because you've removed:

```
<add key="owin:appStartup" value="UmbracoDefaultOwinStartup" />
```

I'm not sure why you've done this, this has completely disabled the Umbraco OWIN startup code. I will reply to your other issue about this.

I will update the documentation to make this clear. The only reason *Identity Extensions* could be used with regards to UmbracoIdentity is because it shows you how to add custom OWIN booting logic. You cannot simply disable Umbraco's OWIN booting sequence = Umbraco will not work.

If you require your own OWIN booting sequence you must ensure that Umbraco's is also initialized. If you install Identity Extensions, you will get a code snippet with a class: `UmbracoStandardOwinStartup`, these snippets include details about what they do. You could use that class to boot your own OWIN logic whilst still ensuring that Umbraco's OWIN startup logic is initialized. 

The main page of this repository mentions the `UmbracoIdentityStartup` which has the logic to boot UmbracoIdentity's OWIN logic - this logic is required for UmbracoIdentity to work. So you'll need to make sure that Umbraco's OWIN logic is initialized, and also UmbracoIdentity's OWIN logic is initialized. This all needs to be done in a single OWIN startup class. There's also additional documentation here:

**Comment by Shazwazza** [comment]
Actually, the documentation is up-to-date. On the main page it specifically talks about OWIN startup - you should follow those instructions.

The `UmbracoIdentityStartup` file that is shipped with UmbracoIdentity already subclasses Umbraco's own `UmbracoDefaultOwinStartup` which ensures the normal Umbraco OWIN logic is initialized.

**Comment by terryclancy** [comment]
Thank you very much Shannon for you prompt response :-)  I do not need think I need any custom  OWIN booting sequence. At this stage I am just trying to get a vanilla version of your code going.

The reason I commented out 

    <add key="owin:appStartup" value="UmbracoDefaultOwinStartup" />

Was because my Startup class (below) was not running.That line of web.config code overrides the startup class.   And the startup class is where I put your initialization code (from the top of the page at https://github.com/Shazwazza/UmbracoIdentity/wiki/Startup-Configuration): Here is my Startup.cs class:

```
using Microsoft.Owin;
using Owin;
using TeraTastic.Models.UmbracoIdentity;
using Umbraco.Core;
using Umbraco.Web.Security.Identity;
using UmbracoIdentity;

[assembly: OwinStartupAttribute(typeof(TeraTastic.Startup))]
namespace TeraTastic
{
    public partial class Startup
    {
        public void Configuration(IAppBuilder app)
        {
            ConfigureAuth(app);

            //Single method to configure the Identity user manager for use with Umbraco
            app.ConfigureUserManagerForUmbracoMembers<UmbracoApplicationMember>();

            //Ensure owin is configured for Umbraco back office authentication
            app.UseUmbracoBackOfficeCookieAuthentication(ApplicationContext.Current);
        }
    }
}
```

I recognize now that this was very much the wrong approach because I inadvertently disabled the Umbraco OWIN startup code.  What is the correct way to get this startup code to run please ?

Sorry for taking your time on what I am sure is a basic question.

Terry Clancy


ClanceZ

**Comment by terryclancy** [comment]
Hi Shannon,

 I think I have this working now after making the following changes
(1) I have been using "Install-Package UmbracoCms" to install Umbraco over a Visual Studio 2015  project creating using the following template: 

    C# / Web / ASP.Net Web Application / ASP.NET 4.6 Templates / MVC with MVC and and Web APIeck boxes selected.    

Now after reading https://our.umbraco.org/documentation/Getting-Started/Setup/Install/install-umbraco-with-nuget I am selecting an "Empty template" and not selecting any of the checkboxes.

(2) Even with that done  the code in your UmbracoIdentityStartup class  was still not running at startup !?  To resolve that I changed the following line in web.config:

    <add key="owin:appStartup" value="UmbracoDefaultOwinStartup" />

to:

    <add key="owin:appStartup" value="TeraTastic.UmbracoIdentityStartup" />

(TeraTastic is my Project Namespace)

Also .... at  this stage I have not added the following lines to the UmbracoIdentityStartup  Class since I do not need Facebook login to Umbraco Backoffice (I am assuming this is OK?):

//Ensure owin is configured for Umbraco back office authentication
app.UseUmbracoBackOfficeCookieAuthentication(ApplicationContext.Current);

I am not sure if (2) above is a result of an error I have made, or if you should update your code or docs to reflect this ?

Thanks again 

Terry Clancy

ClanceZ
