### ISSUE TITLE
Where does UmbracoIDentity persist members of the "IdentityMember" class like PhoneNumber ? 

### ISSUE THREAD

**Issue by terryclancy** [Shazwazza/UmbracoIdentity#37]
Thanks for your help to date - I now have the basics of UmbracoIdentity working with Facebook integration and am working on implementing EmailConfirmation.

I note that UmbracoApplicationMember inherits from UmbracoIdentityMember which inherits from IdentityMember which has several members including for example the string PhoneNumber.

When I include the following code in UmbracoIdentityAccountController.HandleRegisterMember 
        var user = new UmbracoApplicationMember()
        {
            Name = thisUserName,
            UserName = model.UsernameIsEmail || model.Username == null ? model.Email : model.Username,
            Email = model.Email,
            MemberProperties = model.MemberProperties,
            PhoneNumber = "(425)4444490"
        };

I can see the Name and Email stored with the other Member Data in the Umbraco BackOffice - but I do not see (for example) the PhoneNumber there. Why not ? Is it stored somewhere else or do I need to do something to ensure that other standard members of the ASP.Net Identity "IdentityMember" class are persisted ?

Thanks again for your assistance.

Terry Clancy

ClanceZ

**Comment by terryclancy** [comment]
OK...   so I downloaded the source for UmbracoIdentity and Microsoft.Asp.Net.Identity and have been working through it and after tracing through the inheritance relationships etc, from what I can gather:

    UmbracoIdentity.UmbracoMembersUserStore.CreateAsync(T user)

Is where the action occurs in relation to persisting user information during Registration into the Umbraco Member store.  

In that method the following properties are persisted into the Umbraco Member Database (viewable in Umbraco Backoffice)

    UserName
    Email
    Name

The UpdateMemberProperties method is then called which updates some other properties and then  loops though the ASP.Net Identity "User.MemberProperties" and where appropriate copying the value across to the Umbraco "Member" properties and saving it to the member store.

From what I can see my example property of "PhoneNumber" is ignored by this method which answers my question above.

Have I got this right ?

If so I assume that for any properties ignored by Umbraco Identity (or other new Properties) I should just create them in the default Umbraco MemberType and update them independently of UmbracoIdentity - is that correct ?

Thanks again,

Terry Clancy

CLANCEZ

**Comment by Shazwazza** [comment]
If you want to enable things that are not there (i.e. see known issues: https://github.com/Shazwazza/UmbracoIdentity/wiki/Known-Issues) then you'll need to implement this yourself. You have a couple of options:

* Implement your own requirements and override the `UmbracoMembersUserStore` (again see https://github.com/Shazwazza/UmbracoIdentity/wiki/Known-Issues), each requirement is an interface such as `IUserPhoneNumberStore`. You'd need to add these interfaces to your implementation. For example, in the `UmbracoMembersUserStore` you can see it implements the interfaces it supports: https://github.com/Shazwazza/UmbracoIdentity/blob/master/src/UmbracoIdentity/UmbracoMembersUserStore.cs. If you implement the remaining interfaces, you'll need a place to store the info, so you'd have to modify the member type with these new property types to be able to save the information to the member. You'd also need to override `UmbracoMembersUserManager` (https://github.com/Shazwazza/UmbracoIdentity/blob/master/src/UmbracoIdentity/UmbracoMembersUserManager.cs) and return true for the things you are now supporting.
* Or fork this repository and implement the requirements directly (this might even be easier). If you do this, i'd love to see a PR!

**Comment by joshuawheelock** [comment]
Hi Terry,

I've simply extended the default Umbraco Member with the custom properties that I require. I did this in the umbraco backend.

To add these properties upon member creation I simply add each UmbracoProperty to the new user MemberProperties collection. Works perfectly :)

```
UmbracoProperty customProperty= new UmbracoProperty() { Alias = "customPropertyAlias",Name="customPropertyName",Value="valueToStore };

newUser.MemberProperties.Add(customProperty);

var result = await UserManager.CreateAsync(newUser);
```
