### ISSUE TITLE
[AdminTokenAuthorize] - Unauthorized access by scheduled task

### ISSUE THREAD

**Issue by rasmuseeg** [Shazwazza/UmbracoIdentity#38]
I'm using the latest version of UmbracoIdentity and Umbraco 7.3.6.
Our Scheduled tasks are not authorized when requesting a method on UmbracoApiController.
We have tried using [AdminTokenAuthorize] and [Authorize] neither allow the scheduled task user access

Can't find any log details about this. Just that the default:
`Umbraco.Web.Scheduling.ScheduledTasks - rebuildClinicIndex has been called with response: False`

**Comment by Shazwazza** [comment]
What does your UmbracoApiController look like? You need to attribute it with [IsBackOffice] is you want it to authenticate for the back office (which i assume you do). UmbracoIdentity is for front-end members btw, has nothing to do with back office users.

**Comment by rasmuseeg** [comment]
My controller looks like this.
```
    [Authorize]
    [PluginController("Navision")]
    public class ClinicController : UmbracoApiController
    {
      [HttpGet]
        [AllowAnonymous]
        //[AdminTokenAuthorize]
        public HttpResponseMessage RebuildIndex()
        {
            string fileName = System.Web.Hosting.HostingEnvironment.MapPath("~/App_Data/ClinicRebuild.lock");
            FileInfo file = new FileInfo(fileName);
            DateTime lastRebuild = file.LastWriteTime;

            // Should allways run at 00:00, and also if ClinicRebuild.lock is deleted.
            var now = DateTime.Now;
            if((now.Hour == 00 && now.Minute == 00) || file.Exists == false) {
                if (file.Exists == false) {
                    file.Create();
                }

                // Rebuild
                var index = Examine.ExamineManager.Instance.IndexProviderCollection[_clinicIndexerAlias];
                index.RebuildIndex();

                string message = string.Format(
                    "Recieved request to rebuild index at: {0} " + 
                    "last rebuild was: {1}", 
                    DateTime.Now.ToString("dd/MM/yyyy"), 
                    file.LastWriteTime.ToString("dd/MM/yyyy"));

                LogHelper.Info(this.GetType(), message);

                file.LastWriteTime = now;

                return Request.CreateResponse(HttpStatusCode.OK, message);
            }

            return Request.CreateResponse(HttpStatusCode.Forbidden, "You must wait for the right time.");
        }
    }
``` 
I want to protect it from being requested by strangers.

So my guess is that `[Authorize]` is at fault here?

**Comment by Shazwazza** [comment]
Scheduled tasks don't authenticate, they are just public endpoints so there will be no user assigned to this requests (no AuthN) so therefore nothing with be Authorized (Authz). The code that calls the scheduled tasks is baked in to the Umbraco core, it does not set headers or anything so there's not currently a way that the scheduled task endpoint can be auth'd 

A while back there has been some discussion on this internally but unfortunately the priority for this just became so low that it was forgotten. You can see there's notes about this in the Core: https://github.com/umbraco/Umbraco-CMS/blob/dev-v7/src/Umbraco.Web/Scheduling/ScheduledTasks.cs#L14

You'd need to create a feature request for this in the core. Until then you'd need to perform scheduled tasks yourself and if it is an http endpoint, you'd need to secure it yourself.

**Comment by rasmuseeg** [comment]
Thanks :+1:, you're the best!

http://issues.umbraco.org/issue/U4-7886
