### ISSUE TITLE
Create a UmbracoIdentity.CoreBinaries nuget file

### ISSUE THREAD

**Issue by mattbrailsford** [Shazwazza/UmbracoIdentity#40]
Relates to  #22, but I'm coming at it from a different angle. 

Provide a nuget package for just the core binaries so that if you want to develop a package that relies on UmbracoIdentity you don't have it generating all the web folders in the project. I just want to dll references.

**Comment by Shazwazza** [comment]
Yup i understand what you mean. Gotta try to get a couple releases out of my other projects and then back to all this identity stuff!

**Comment by rasmuseeg** [comment]
#22 Related

**Comment by rasmuseeg** [comment]
@mattbrailsford Yes, and propperly a better one.

**Comment by Shazwazza** [comment]
For the upcoming version (4.0.0) there will be 2x Nuget package:

* UmbracoIdentity.Core = just the DLLs
* UmbracoIdentity = requires UmbracoIdentity.Core and contains all of the template files

**Comment by alindgren** [comment]
I'd like to see this too 👍

**Comment by Shazwazza** [comment]
This was previously completed in 4.0.0 release
