### ISSUE TITLE
No way to override some classes

### ISSUE THREAD

**Issue by erinloy** [Shazwazza/UmbracoIdentity#5]
No easy way to override IExternalLoginStore and UmbracoMembersUserManager when using UmbracoIdentity (via NuGet binary = no source).  Had to copy the source from AppBuilderExtensions and modify ConfigureUserManagerForUmbraco to use my classes.  An overloaded version of ConfigureUserManagerForUmbraco that allows these classes (or factory functions) to be supplied would be helpful.

**Comment by Shazwazza** [comment]
Fixed in bb1db2806485f17e8803464ed274d177f9837519
