### ISSUE TITLE
Question: Bearer tokens?

### ISSUE THREAD

**Issue by nojaf** [Shazwazza/UmbracoIdentity#50]
Hi, would this package also work if you configured the Startup.cs to use bearer tokens instead of cookies? And then just create a WebApi controller similar to UmbracoIdentityAccountController.cs?

**Comment by Shazwazza** [comment]
Yes sure, two things are happening here: AuthN (Authentication --> cookies/bearer tokens/etc...) and AuthZ (authorizing the user assigned in AuthN)

The AuthZ part should never have to really change based on how your app is authenticating

**Comment by nojaf** [comment]
Cool, thanks!
