### ISSUE TITLE
Changing the "RememberMe" "ExpireTimeSpan" 

### ISSUE THREAD

**Issue by terryclancy** [Shazwazza/UmbracoIdentity#51]
For ASP.Net Identity what is the default "RememberMe" "ExpireTimeSpan" an how should I change that please ?  Should I use approach detailed at:

http://stackoverflow.com/questions/22944783/how-to-set-timeout-for-owincontext-in-mvc-5 ?

Terry Clancy
ClanceZ

**Comment by terryclancy** [comment]
Never Mind - I figured it out.  For reference in UmbracoIdentityStartup.cs  I changed the following:

            app.UseCookieAuthentication(
                        //You can modify these options for any customizations you'd like
                        new FrontEndCookieAuthenticationOptions());

to this:

            app.UseCookieAuthentication(
                        //You can modify these options for any customizations you'd like
                        new FrontEndCookieAuthenticationOptions
                        {
                            SlidingExpiration = true,
                            ExpireTimeSpan = System.TimeSpan.FromMinutes(5),      // .FromDays(30),
                            AuthenticationType = DefaultAuthenticationTypes.ApplicationCookie,
                            LoginPath = new PathString("/user/login"),
                        });

Hope this helps, let me know if you see any issues.

Thanks

Terry Clancy
ClanceZ

**Comment by Shazwazza** [comment]
Glad you found it :)
