### ISSUE TITLE
Is there a good example?

### ISSUE THREAD

**Issue by biapar** [Shazwazza/UmbracoIdentity#65]
Is there a good example?

**Comment by Shazwazza** [comment]
A good example of what? You really need to start adding some details to your bug reports ;)

**Comment by biapar** [comment]
Sorry: a good example of how to configure and use and if this type of authentication works with normal Umbraco membership. Could an user enter with Umbraco member login and after add its OAuth social auth?

**Comment by Shazwazza** [comment]
There's a wonderful example when you install the package and follow the installation instructions. It will give you a fully functional view + code for everything: Login, logout, register, update, register with OAuth, link/unlink OAuth, change password, etc...
