### ISSUE TITLE
Security Stamp Field: How to generate a GUID when create member from backoffice ( think to a "stupid" admin )?

### ISSUE THREAD

**Issue by biapar** [Shazwazza/UmbracoIdentity#68]
Security Stamp Field: How to generate a GUID when create member from backoffice without to put in the data ( think to a "stupid" admin )?

**Comment by Shazwazza** [comment]
All fixed up and will be in the 6.0.0 release, when a member is being saved and there's a security stamp property available but it is empty, one will be generated.
