### ISSUE TITLE
How to enable account confirmation

### ISSUE THREAD

**Issue by markwemekamp** [Shazwazza/UmbracoIdentity#70]
Hi Shannon,
First of all, I really like the package. Great job.

I'm looking for a way to enable the account confirmation functionality.
I've read the [Microsoft article](http://go.microsoft.com/fwlink/?LinkID=320771) on this
I've enabled the functionality in the Controller, changed the callback url to the SurfaceController:

`var callbackUrl = Url.SurfaceAction<UmbracoIdentityAccountController>("ConfirmEmail", new {userId = user.Id, code = code});`

And added a new method named ConfirmEmail to the Controller:

```[AllowAnonymous]
        public async Task<ActionResult> ConfirmEmail(int userId, string code)
        {
                var result = await UserManager.ConfirmEmailAsync(userId, code);
                if (result != null && result.Succeeded)
                {
                    //
                }
        }
```

The code gets called and UserManager.ConfirmEmailAsync is called. 
This calls a method named **SetEmailConfirmedAsync** on UmbracoMembersUserStore, which throws a NotImplementedException

Now the real question:
Do I have to create my own implementation of the UserStore (since I can't inherit because the method is not marked virtual) or is there a better/easier way of doing this?

**Comment by markwemekamp** [comment]
Ok after reading the Known Issues section in the wiki, I guess I'm going to implement this myself :)

**Comment by Shazwazza** [comment]
Hi, yeah sorry it's not implemented but just because a method isn't marked as virtual doesn't mean you can't override it! The method is part of the underlying interface so you can explicitly implement this interface method in your subclass, this actually 'overrides' the underlying non-virtual method.

**Comment by markwemekamp** [comment]
Thanks for the response. 
I discovered the method is part of the IUserEmailStore interface just after I posted the above question, so ended up inheriting from UmbracoMembersUserManager and implementing IUserEmailStore. Works as a charm now :)
