### ISSUE TITLE
ExternalLoginStore issue with Umbraco 7.6.0

### ISSUE THREAD

**Issue by yuriburger** [Shazwazza/UmbracoIdentity#72]
Hi,

When using UmbracoIdentity 5.0.0 with Umbraco 7.6.0 I run into the following error(s):

Exception Details: System.NullReferenceException: Object reference not set to an instance of an object.
Line 100:
Line 101:            // Sign in the user with this external login provider if the user already has a login
Line 102:            var user = await UserManager.FindAsync(loginInfo.Login);
Line 103:            if (user != null)
Line 104:            {

Source File: E:\Sources\POC1\POC1.Umbraco76\Controllers\UmbracoIdentityAccountController.cs    Line: 102 

Stack Trace: 

[NullReferenceException: Object reference not set to an instance of an object.]
   Umbraco.Core.Persistence.Database.BeginTransaction(IsolationLevel isolationLevel) +84
   UmbracoIdentity.ExternalLoginStore.EnsureTable() in X:\Projects\Umbraco\UmbracoIdentity\src\UmbracoIdentity\ExternalLoginStore.cs:116
   UmbracoIdentity.ExternalLoginStore.<EnsureInitialized>b__12_0() in X:\Projects\Umbraco\UmbracoIdentity\src\UmbracoIdentity\ExternalLoginStore.cs:103
   System.Threading.LazyInitializer.EnsureInitializedCore(T& target, Boolean& initialized, Object& syncLock, Func`1 valueFactory) +115
   UmbracoIdentity.ExternalLoginStore.EnsureInitialized() in X:\Projects\Umbraco\UmbracoIdentity\src\UmbracoIdentity\ExternalLoginStore.cs:100
   UmbracoIdentity.ExternalLoginStore.Find(UserLoginInfo login) in X:\Projects\Umbraco\UmbracoIdentity\src\UmbracoIdentity\ExternalLoginStore.cs:162
   UmbracoIdentity.UmbracoMembersUserStore`1.FindAsync(UserLoginInfo login) in X:\Projects\Umbraco\UmbracoIdentity\src\UmbracoIdentity\UmbracoMembersUserStore.cs:358
   Microsoft.AspNet.Identity.UserManager`2.FindAsync(UserLoginInfo login) +59

Steps to reproduce:

1. New setup Umbraco CMS 7.6.0 using Nuget package
2. SQL Server or SQL CE (both throw this error)
3. Install-Package Microsoft.Owin.Security.OpenIDConnect
4. Install-Package UmbracoIdentity
5. Configure external identity provider using:

    app.UseExternalSignInCookie(DefaultAuthenticationTypes.ExternalCookie);
    var identityOptions = new OpenIdConnectAuthenticationOptions
    {
    ClientId = "xyz",
    AuthenticationType = "IdentityServer",
    Authority = "https://localhost:44349/core",
    RedirectUri = "http://localhost:32794/",
    ResponseType = "code id_token token",
    Scope = "openid profile email",
    PostLogoutRedirectUri = "http://localhost:32794/"
    };
    app.UseOpenIdConnectAuthentication(identityOptions);

6. Try to login. On return from our external identity provider, the error is shown.

Any help appreciated!

/Y.

**Comment by Shazwazza** [comment]
This is fixed now, i've setting this to a breaking change since some of the constructor overloads have been changed and I've bumped the min version of Umbraco to 7.6 for this next major version release.

**Comment by Shazwazza** [comment]
I'll release a 6.0.0 of this tomorrow hopefully,

You can test the latest build by installing the latest nightly nuget package:

```
Install-Package UmbracoIdentity -Source https://ci.appveyor.com/project/Shandem/umbracoidentity/build/artifacts -Pre
```

The new nuget requires >= Umbraco 7.6.0

**Comment by yuriburger** [comment]
Thanks! I will grab the nightly.

**Comment by Shazwazza** [comment]
@yuriburger great, please let me know if you have success with that

**Comment by yuriburger** [comment]
@Shazwazza first tests look good thanks for working on this

**Comment by Shazwazza** [comment]
Cool, v6.0.0 is out on nuget now
