### ISSUE TITLE
Error After Installation

### ISSUE THREAD

**Issue by sadeghhp** [Shazwazza/UmbracoIdentity#76]
In Umbraco 7.6.1 after installing this package , my home page show this:

Server Error in '/' Application.
Could not convert the id 0945f50c-26cd-4315-8cca-70dda069d71c to type System.Int32

Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code. 

Exception Details: System.InvalidOperationException: Could not convert the id 0945f50c-26cd-4315-8cca-70dda069d71c to type System.Int32

Source Error: 

An unhandled exception was generated during the execution of the current web request. Information regarding the origin and location of the exception can be identified using the exception stack trace below.

**Comment by Shazwazza** [comment]
Sorry about the insane delay on replying. I have not seen this issue reported elsewhere and I cannot replicate. If you can still replicate the problem with the latest Umbraco and UmbracoIdentity packages feel free to re-open with steps to replicate.
