### ISSUE TITLE
Could not convert the id "GUID" to type System.Int32

### ISSUE THREAD

**Issue by rakeshkhoodeeram** [Shazwazza/UmbracoIdentity#83]
Hello,
I am getting the following error, after leaving the site idle for sometime.
![image](https://user-images.githubusercontent.com/3471148/34864391-745a86d2-f78d-11e7-8c7e-70b78fa6b155.png)

Is there anything I need to change?

**Comment by Shazwazza** [comment]
Do you have steps to replicate from a vanilla Umbraco install? 
Do you have details on what versions of everything you are using?
Details on your setup, etc... ?

**Comment by Shazwazza** [comment]
Closing this for now, if you have steps to reproduce let me know
