### ISSUE TITLE
Integration with Identity Server

### ISSUE THREAD

**Issue by stokesy43** [Shazwazza/UmbracoIdentity#84]
Hi @Shazwazza ,

I've written a blog post on how to integrate this package with Identity Server.  

[Blog Post](https://pstokes.co.uk/posts/umbraco-members-and-identity-server-part-1/)

Is this something that might be worthwhile while adding to the core package or perhaps as an extension.

Cheers
Stokesy

**Comment by Shazwazza** [comment]
Very nice! I haven't had time to digest the entire thing but certainly it would be great to add any re-usable snippets and docs to this package to get people up and running much quicker just like we have for some other OAuth providers/snippets shipping with this.

**Comment by Shazwazza** [comment]
Ah, just reailzed I've confused myself with what this package ships with :) We could definitely add more functionality, snippets, docs to this codebase and then ship `UmbracoIdentity.IdentityServer` as a separate Nuget package if that makes more sense.

**Comment by stokesy43** [comment]
Yes makes sense as a separate nuget package as it requires other OpenId/OAuth packages not required by the main package so no point polluting that.  I'll knock something up and get back to you. 

The blog was written in [Articulate](https://github.com/Shazwazza/Articulate) btw and I'm going to write some more articles soon

**Comment by stokesy43** [comment]
Apologies for the delay, my contract was finishing and wanted to focus on handover.  

All clear of that now so I've knocked up a  [nuget package](https://www.nuget.org/packages/UmbracoIdentity.IdentityServer)

@Shazwazza how would you like the documentation to work on this?

**Comment by biapar** [comment]
UaU! Intresting for Umbraco members! @stokesy43 Where are part 2 and 3?

**Comment by stokesy43** [comment]
Parts 2 & 3 aren't really related to UmbracoIdentity per se so I didn't want to pollute this conversation with something unrelated.  But seeing as you asked ...

Part 2
https://pstokes.co.uk/posts/umbraco-members-and-identity-server-part-2

Part 3
https://pstokes.co.uk/posts/umbraco-members-and-identity-server-part-3/

**Comment by Shazwazza** [comment]
Have updated the wiki with references to your blog/nuget package, etc... https://github.com/Shazwazza/UmbracoIdentity/wiki/External-Authentication-(OAuth)

Feel free to update it with any changes/info you want!
