### ISSUE TITLE
Help with the quick start

### ISSUE THREAD

**Issue by johanalkstal** [Shazwazza/UmbracoIdentity#85]
I've followed the instructions on the wiki and a testing the quick start instructions.

I'm getting an error that I can't understand (I'm also new to Umbraco),
so I would really appreciate help explaining and understanding what's going on here.

I get an exception from Account.cshtml and the line

`@Html.Partial("~/Views/UmbracoIdentityAccount/ExternalLoginsList.cshtml", new ExternalLoginListViewModel { Action = "ExternalLogin" })`

`System.Web.HttpCompileException: 'c:\Users\Johan Alkstål\AppData\Local\Temp\Temporary ASP.NET Files\vs\9f45840d\c68e0e2\App_Web_externalloginslist.cshtml.46b5d27c.snvxpjhg.0.cs(48): error CS0426: Type name Web does not exist in type Umbraco.Web.PublishedContentModels.Home.'
`

**Comment by johanalkstal** [comment]
Removed UmbracoIdentity for now and experimenting with other options.

**Comment by Shazwazza** [comment]
This error:

> Type name Web does not exist in type Umbraco.Web.PublishedContentModels.Home.'

is caused by Models Builder in Umbraco. I'm just going to test with Umbraco vLatest and see if I can replicate, it could be something has changed in Umbraco in recent versions and nobody has reported this.

**Comment by Shazwazza** [comment]
I have followed the Quick Start guide exactly as specified and it works as expected with Umbraco 7.8.1 and UmbracoIdentity 6.0.0. 

Perhaps you can try again? 

The error you are getting is from ModelsBuilder. Maybe it's a conflict in the name/namespace of your project. What did you name your project/solution when testing this?

**Comment by Shazwazza** [comment]
Also note I've updated the readme/install instructions: https://github.com/Shazwazza/UmbracoIdentity/blob/master/README.md#installation
