### ISSUE TITLE
How to use UmbracoIdentity together with UmbracoIdentityExtensions?

### ISSUE THREAD

**Issue by johanalkstal** [Shazwazza/UmbracoIdentity#86]
I have added UmbracoIdentityExtensions and can sign in to the backoffice alright.

Now I want to use Azure AD to automatically sign users in without a custom login view.

At the same time, I see that both this library and the extensions library need to set `owin:appStartup` in web.config.

So my question is how do I best combine these two libraries to provide me with Azure AD logins to both backoffice and frontend?

And can I do this without adding a login view for frontend members?

**Comment by Shazwazza** [comment]
Owin only has one startup, so you'll need to combine the use cases for both of these as you see fit.

The configuration code for back end users and front-end members are totally separate calls. 

Depending on your requirements, certain code blocks need to be registered before others. IIRC the back office cookie authentication calls need to come before the front-end members authentication calls.

**Comment by Shazwazza** [comment]
To be clear:

* `UmbracoIdentityExtensions` = extension methods for configuring __back office user__ authentication 
* `UmbracoIdentity` = Umbraco __front-end members__ with ASP.NET Identity
