### ISSUE TITLE
external provider integration - external/internal linkage?

### ISSUE THREAD

**Issue by mistyn8** [Shazwazza/UmbracoIdentity#88]
Hi, I've followed all the installation instructions and have a working account page, apart from the external providers.. 
I think I must be missing something on that front.

I've gone with google, uncommenting these lines from App_Start/UmbracoIdentitiyStartup.cs
```
app.UseExternalSignInCookie(DefaultAuthenticationTypes.ExternalCookie);
app.UseGoogleAuthentication(clientId: "XXX", clientSecret: "XXX");
```

So when not logged in via default umbracoMember, hitting the google button, takes me off to the google authentication process, and I can pass that (both standard and a two factor google user)
On completion I'm still at the account page, with no indication that I logged in or failed.

Logs show
```
2018-05-09 17:39:47,472 [P16508/D3/T63] ERROR Umbraco.Core.Logging.OwinLogger - Event Id: 0, state: Authentication failed
System.Net.Http.HttpRequestException: Response status code does not indicate success: 403 (Forbidden).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at Microsoft.Owin.Security.Google.GoogleOAuth2AuthenticationHandler.<AuthenticateCoreAsync>d__0.MoveNext()
```
Clicking the goggle button though at this point doesn't take me to the google login process again, though does generate the error. Only by removing cookies for the site can I get that to happen again.

I'm sure I'm just missing that final piece in the jigsaw, namely how an umbraco member is associated with the google account? Is it by matching email, username or is there a manual linkage that is required (like with the admin user mapping?)

Thanks for any guidance on this!

**Comment by Shazwazza** [comment]
Did you try registering a member normally and once logged in then you link the account with Google (etc). Then you should be able to login with Google. I can't remember if the code as-is, allows you to register a new member directly from signing in via external providers. This is of course possible but perhaps the code shipped hasn't implemented this.

**Comment by mistyn8** [comment]
I feel like I'm missing something in the process here for the linking..
I can't see anything in the member admin area (like on the user dialogue) to be able to link a google account.
Are you saying that from the account page that I should login as a registered umbraco user.. and then click the login as google and that will link at that point?
If I go in that direction I get "An error occurred, could not get external login info".

**Comment by mistyn8** [comment]
If it helps solve where I'm going wrong I can see that the googleuser account that I'm using does show that the app I've created has access.

**Comment by mistyn8** [comment]
stumbled across this post #34 where google+ api needs to be added to the app... 
I can't see it mentioned in the https://developers.google.com/identity/protocols/OpenIDConnect#getcredentials

But all working now, and see that the flow is try to login as google, authenticate then register a new user with that linkage.

**Comment by Shazwazza** [comment]
Glad you got it sorted. You can link/unlink accounts after as a member after you've logged in or registered too.
