### ISSUE TITLE
HTTPPost rather than GET authentication paramaters to an external provider?

### ISSUE THREAD

**Issue by mistyn8** [Shazwazza/UmbracoIdentity#90]
I have managed to set up a login page that fires on protected page access, so straight off to the external provider rather than via a button...

eg
 @Html.Action("ExternalDirectLogin", "UmbracoIdentityAccount", new { provider = "OpenIdConnect"})

However, this results in a not so friendly GET process, is there a way to do this over POST?
thanks.

**Comment by Shazwazza** [comment]
if you've setup your action `ExternalDirectLogin` to accept POST, then to submit a POST request in HTML you need to use a form. As an example see https://github.com/Shazwazza/UmbracoIdentity/blob/6422a796db0ecdc612f42f9917f0b88a8eeaaf26/src/UmbracoIdentity.Web/Views/UmbracoIdentityAccount/LoginStatus.cshtml#L30
