### ISSUE TITLE
Owin with Identity Server 4 - cancel login causes error

### ISSUE THREAD

**Issue by mistyn8** [Shazwazza/UmbracoIdentity#91]
```
"OpenIdConnectMessage.Error was not null, indicating an error. Error: 'access_denied'. Error_Description (may be empty): ''. Error_Uri (may be empty): ''."
```
External authentication all implemented fine.. However, there is an option to cancel login on the identity server side, which then redirects back to the umbraco app but causes the above error.

I don't seem to be able to catch this error in the ExternalLoginCallback method, any pointers where I could look?

**Comment by stokesy43** [comment]
I know this is a couple of months old now but I thought I'd post the solution in case your still searching or anyone else comes across this.

You need to subscribe to the AuthenticationFailed notification on the OpenIdConnectAuthenticationNotifications.

i.e. your UmbracoIdentityStartup.cs will look something like this ...

```
app.UseOpenIdConnectAuthentication(new OpenIdConnectAuthenticationOptions
            {
                Authority = "http://localhost:5000/",
                ClientId = "umbraco",
                RedirectUri = "http://localhost:5010/",
                ResponseType = "id_token",
                Scope = "openid profile email",
                Notifications = new OpenIdConnectAuthenticationNotifications
                {
                    AuthenticationFailed = async n =>
                    {
                        if (string.Equals(n.ProtocolMessage.Error, "access_denied", StringComparison.Ordinal))
                        {
                            n.HandleResponse();

                            n.Response.Redirect("/");
                        }
                    },
                    SecurityTokenValidated = async n =>
                    {
                        etc.
```

Hope this helps

**Comment by Shazwazza** [comment]
@stokesy43  Thanks for providing some info to other members! Just wondering if you might have time to help document integrating with Identity Server on the wiki? https://github.com/Shazwazza/UmbracoIdentity/wiki/External-Authentication-(OAuth)

**Comment by Shazwazza** [comment]
Ha! sorry just realized we've sort of chatted about this a bit https://github.com/Shazwazza/UmbracoIdentity/issues/84  I'll read through your posts and maybe just update the wiki to point to your blog
