### ISSUE TITLE
Umbraco v8 compatibility

### ISSUE THREAD

**Issue by PTwr** [Shazwazza/UmbracoIdentity#94]
Nothing surprising here as v8 just came out.

Issue: Current version is not compatible with Umbraco v8. Nuget installation fails but gracefully reverts.

Expected behavior: Being able to install UmbracoIdentity in Umbraco v8 via Nuget ;)

Is update to v8 in plans? If so, when can it be expected?

**Comment by Shazwazza** [comment]
Yup i just need to get it done. If you have time it probably wouldn't be terribly difficult to get it running on v8 and PRs are always much appreciated :) Otherwise I'll try to have something ready before the month ends.

**Comment by PTwr** [comment]
I tested it a bit, code looks to be compatible but updating Nuget in existing project fails due to different .NET versions. I am a bit short on time this week but I'll try to find sometime for fiddling.

**Comment by osigas** [comment]
I've made a start on it in https://github.com/osigas/UmbracoIdentity, got it mostly converted apart from the UmbracoBackOfficeAuthenticationHandler. Looks like there's been some changes to the UmbracoBackOfficeIdentity that means we can't easily get the back office Identity reference from just the Forms auth ticket, unless I'm mistaken?

**Comment by chrno1209** [comment]
Hi, any move on this topic please?
@osigas did you make your folk work? I will have a try tonight.

**Comment by algeerto** [comment]
Just curious as to the status of this - any progress?

**Comment by Shazwazza** [comment]
@osigas are you able to submit a PR so we can review from there?

**Comment by osigas** [comment]
It's very rough around the edges and I've not been able to look at it in a while but I've done a PR with what I had.

**Comment by Shazwazza** [comment]
Tested everything now on 8 and 8.1 and it all works with the output nuget package 🎉
