### ISSUE TITLE
Umbraco v7.13 & StructureMap v4.7

### ISSUE THREAD

**Issue by CodeCheetah** [Shazwazza/UmbracoIdentity#95]
Hi Shannon,

Is there any example of how I can integrate it with StructureMap DI?

I'm having trouble setting UmbracoMembersUserStore<UmbracoIdentityMember>.

Thanks.

**Comment by Shazwazza** [comment]
I've never used StructureMap so i have no idea, sorry.

Perhaps if you explained the problem i might be able to give you some pointers.

**Comment by CodeCheetah** [comment]
Hi Shannon,

No problem, I have managed to wire it up with the following:

`For<IUserStore<UmbracoApplicationMember, int>>().Use<UmbracoMembersUserStore<UmbracoApplicationMember>>();`

I kept getting 'Cannot use ASP.Net Identity with UmbracoMemberUserStore when the password format in not Hashed'

With reference to https://our.umbraco.com/forum/extending-umbraco-and-using-the-api/77047-umbracoidentity-and-custom-members

I have cloned the repository and added the following to IdentityEnabledMembersMembershipProvider.

`public override MembershipPasswordFormat PasswordFormat => MembershipPasswordFormat.Hashed;`

**Comment by Shazwazza** [comment]
Cool, i can update the code to always force it as hashed, have also replied on the thread here: https://our.umbraco.com/forum/extending-umbraco-and-using-the-api/77047-umbracoidentity-and-custom-members#308474

**Comment by Shazwazza** [comment]
See https://github.com/Shazwazza/UmbracoIdentity/issues/99
